version: '3'
services:
  server:
    container_name: backup_server
    image: backup-server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_IP=backup_server
      - SERVER_PORT=12345
      - SERVER_LISTEN_BACKLOG=5
    networks:
      - company_net

  company_server_1:
    container_name: company_server_1
    image: company-server:latest
    entrypoint: python3 /main.py
    environment:
      - BACKUP_REQUESTS_PORT=12345
      - COMPANY_LISTEN_BACKLOG=5
    networks:
      - company_net
    volumes:
    - "./volumes/company_server_1:/files"

networks:
  company_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24